services:
  warproxy.server:
    image: ghcr.io/thainguyen06/warproxy:latest
    restart: always
    environment:
      - WARP_PLUS=true
      - HTTP_PORT=1081
    ports:
      - 1080:1080
      - 1081:1081
    entrypoint:
      - /init
      - " && "
      - /usr/local/bin/new_warp_connection.sh
networks: {}
